server:
  port: ${PORT:8080}

timefold:
  solver:
    solution-class: com.example.timefold.domain.Roster
    entity-class-list:
      - com.example.timefold.domain.ShiftAssignment
    constraint-provider-class: com.example.timefold.solver.RosterConstraintProvider
    termination:
      spent-limit: 5s
